# Format:

# - setname:
#     grid_size: int                          # Grid size
#     blobs_density: float                    # Density of blobs (from grid size **squared**)
#     mf_ratio: float                         # Male / female ratio
#     survival_chance: { m: float, f: float } # Chances of surviving each day for each gender
#     expected_death: { m: int, f: int }      # Expected age of death for each gender
#     death_variance: int or float            # Variance in expected age of death
#     birth_chance: float                     # Chances of a blob giving birth when all the conditions are met
#     pregnancy_death_chance: float           # Chances of a pregnant blob to die
#     blob_init_energy: int                   # Initial blob energy
#     blob_live_energy: int                   # Energy living costs to a blob (needs to be negative for it to lose energy)
#     travel_energy: int or float             # Energy moving costs to a blob
#     max_travel: int                         # Maximum travel distance per move
#     food_availability: float                # Food percentage depending on the amount of blobs
#     food_energy: int or float               # Amount of energy a cell of food gives
#     food_regeneration: int                  # Percentage of food regenerating each day depending on the current amount of food
#     death_energy_factor: float              # Percentage of energy a weaker blob gives to the winner of a battle
#     n_days: int                             # Total number of days
---
highweak:
    grid_size: 100
    blobs_density: 0.005
    mf_ratio: 0.5
    survival_chance: { m: 0.99999, f: 0.99998 }
    expected_death: { m: 100, f: 120 }
    death_variance: 3
    birth_chance: 0.8
    pregnancy_death_chance: 0.01
    blob_init_energy: 100
    blob_live_energy: -1
    max_travel: 10
    travel_energy: -0.1
    food_availability: 0.5
    food_energy: 100
    food_regeneration: 0.05
    death_energy_factor: 0.5
    n_days: 10000
lowstrong:
    grid_size: 100
    blobs_density: 0.05
    mf_ratio: 0.5
    survival_chance: { m:0.99, f:0.98 }
    expected_death: { m:15, f:18 }
    death_variance: 3
    birth_chance: 0.1
    pregnancy_death_chance: 0.01
    blob_init_energy: 100
    blob_live_energy: -5
    max_travel: 10
    travel_energy: -0.5
    food_availability: 10
    food_energy: 20
    food_regeneration: 0.05
    death_energy_factor: 0.5
    n_days: 10000